### ISSUE TITLE
submodule uses none-publicly accessible git clone link

### ISSUE THREAD

**Issue by keightyfive** [SacBase/cmake-common#2]
git@github.com:SacBase/cmake-common.git does not work if you are not a member of Sac group...

**Comment by ashinkarov** [comment]
In sac packages, cmake-common should be used via https://github.com/SacBase/cmake-common.git
If it is not, please submit an issue to the module where this is not the case.
This has nothing to do with cmake-common itself.

**Comment by hv15** [comment]
@ashinkarov I created the issue as a reminder, but yes we need to identify the repos that this affects... I think actually that is it all of them. I'll look at this later.
